// ============================================================
// agent.proto — Agent 与 Controller 之间的设备管理通信定义
//
// 为什么需要这个文件？
//   设备注册、心跳、注销是独立于任务执行的基础协议层。
//   把它们和 task.proto 分开，因为两者的变更频率不同：
//   设备管理协议一旦稳定很少改动，任务协议会随着功能迭代频繁变化。
// ============================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: localpilot/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamType int32

const (
	StreamType_STREAM_TYPE_UNSPECIFIED StreamType = 0
	StreamType_STREAM_TYPE_STDOUT      StreamType = 1
	StreamType_STREAM_TYPE_STDERR      StreamType = 2
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "STREAM_TYPE_UNSPECIFIED",
		1: "STREAM_TYPE_STDOUT",
		2: "STREAM_TYPE_STDERR",
	}
	StreamType_value = map[string]int32{
		"STREAM_TYPE_UNSPECIFIED": 0,
		"STREAM_TYPE_STDOUT":      1,
		"STREAM_TYPE_STDERR":      2,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_localpilot_v1_agent_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_localpilot_v1_agent_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{0}
}

// DeviceInfo: 描述一台计算设备的所有静态能力
// 为什么需要这么多字段？
//
//	调度器需要足够的信息来决定"这个任务该分配给谁"
//	比如 GPU 任务不能发给树莓派，ARM 二进制不能发给 x86 设备
type DeviceInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Hostname          string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                            // 设备主机名，如 "pi4-livingroom"
	Os                string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                                        // 操作系统，如 "linux" / "macos" / "windows"
	Arch              string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`                                                    // CPU 架构，如 "x86_64" / "aarch64" / "armv7l"
	CpuCores          uint32                 `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                           // 逻辑 CPU 核心数
	TotalRamBytes     uint64                 `protobuf:"varint,5,opt,name=total_ram_bytes,json=totalRamBytes,proto3" json:"total_ram_bytes,omitempty"`          // 总内存（字节）
	GpuInfo           string                 `protobuf:"bytes,6,opt,name=gpu_info,json=gpuInfo,proto3" json:"gpu_info,omitempty"`                               // GPU 信息，如 "Apple M1" / "NVIDIA RTX 3060" / "" (无 GPU)
	SupportedRuntimes []string               `protobuf:"bytes,7,rep,name=supported_runtimes,json=supportedRuntimes,proto3" json:"supported_runtimes,omitempty"` // 支持的运行时，如 ["docker", "process"]
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *DeviceInfo) GetTotalRamBytes() uint64 {
	if x != nil {
		return x.TotalRamBytes
	}
	return 0
}

func (x *DeviceInfo) GetGpuInfo() string {
	if x != nil {
		return x.GpuInfo
	}
	return ""
}

func (x *DeviceInfo) GetSupportedRuntimes() []string {
	if x != nil {
		return x.SupportedRuntimes
	}
	return nil
}

// ResourceUsage: 描述设备当前资源使用情况
// 所有百分比为 0.0 ~ 1.0 的浮点数
type ResourceUsage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent            float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`                                    // CPU 使用率，0.0 ~ 1.0
	UsedRamBytes          uint64                 `protobuf:"varint,2,opt,name=used_ram_bytes,json=usedRamBytes,proto3" json:"used_ram_bytes,omitempty"`                             // 已用内存（字节）
	UsedDiskBytes         uint64                 `protobuf:"varint,3,opt,name=used_disk_bytes,json=usedDiskBytes,proto3" json:"used_disk_bytes,omitempty"`                          // 已用磁盘（字节）
	CpuTemperatureCelsius float32                `protobuf:"fixed32,4,opt,name=cpu_temperature_celsius,json=cpuTemperatureCelsius,proto3" json:"cpu_temperature_celsius,omitempty"` // CPU 温度（摄氏度），不可用时为 -1
	RunningTaskCount      uint32                 `protobuf:"varint,5,opt,name=running_task_count,json=runningTaskCount,proto3" json:"running_task_count,omitempty"`                 // 当前正在执行的任务数
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceUsage) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetUsedRamBytes() uint64 {
	if x != nil {
		return x.UsedRamBytes
	}
	return 0
}

func (x *ResourceUsage) GetUsedDiskBytes() uint64 {
	if x != nil {
		return x.UsedDiskBytes
	}
	return 0
}

func (x *ResourceUsage) GetCpuTemperatureCelsius() float32 {
	if x != nil {
		return x.CpuTemperatureCelsius
	}
	return 0
}

func (x *ResourceUsage) GetRunningTaskCount() uint32 {
	if x != nil {
		return x.RunningTaskCount
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // 设备的静态能力信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DeviceId             string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                        // Controller 分配的唯一设备 ID（UUID）
	HeartbeatIntervalSec uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"` // Controller 要求的心跳间隔（秒）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                // Controller 分配的设备 ID
	ResourceUsage *ResourceUsage         `protobuf:"bytes,2,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"` // 当前资源使用情况
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HeartbeatRequest) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{5}
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 要注销的设备 ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                     // 下线原因，如 "user_shutdown" / "maintenance"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // Controller 是否确认注销
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DeregisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                       // 任务 ID（Controller 分配）
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                                                   // 要执行的命令，如 "ffmpeg"
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`                                                                         // 命令参数，如 ["-i", "video.mp4", "-vf", "scale=1920:1080", "output.mp4"]
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 环境变量
	InputFileUrls  []string               `protobuf:"bytes,5,rep,name=input_file_urls,json=inputFileUrls,proto3" json:"input_file_urls,omitempty"`                                // 输入文件的下载地址（从 Controller 文件服务器拉取）
	ResourceLimits *ResourceLimits        `protobuf:"bytes,6,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`                               // 资源限制（定义在 task.proto 中，import 复用）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetInputFileUrls() []string {
	if x != nil {
		return x.InputFileUrls
	}
	return nil
}

func (x *ExecuteRequest) GetResourceLimits() *ResourceLimits {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

type LogChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                            // 所属任务 ID
	StreamType      StreamType             `protobuf:"varint,2,opt,name=stream_type,json=streamType,proto3,enum=localpilot.v1.StreamType" json:"stream_type,omitempty"` // stdout 还是 stderr
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                              // 日志内容（bytes 避免 UTF-8 校验问题）
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`              // Agent 侧时间戳（毫秒）
	SeqNum          int64                  `protobuf:"varint,5,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`                                           // 序号，从 0 开始递增，用于排序和丢包检测
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LogChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogChunk) GetStreamType() StreamType {
	if x != nil {
		return x.StreamType
	}
	return StreamType_STREAM_TYPE_UNSPECIFIED
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *LogChunk) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 要取消的任务 ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`               // 取消原因，如 "user_cancelled" / "device_offline_migration"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // Agent 是否接受了取消请求
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_localpilot_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CancelTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_localpilot_v1_agent_proto protoreflect.FileDescriptor

const file_localpilot_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x19localpilot/v1/agent.proto\x12\rlocalpilot.v1\x1a\x18localpilot/v1/task.proto\"\xdb\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\rR\bcpuCores\x12&\n" +
	"\x0ftotal_ram_bytes\x18\x05 \x01(\x04R\rtotalRamBytes\x12\x19\n" +
	"\bgpu_info\x18\x06 \x01(\tR\agpuInfo\x12-\n" +
	"\x12supported_runtimes\x18\a \x03(\tR\x11supportedRuntimes\"\xe4\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12$\n" +
	"\x0eused_ram_bytes\x18\x02 \x01(\x04R\fusedRamBytes\x12&\n" +
	"\x0fused_disk_bytes\x18\x03 \x01(\x04R\rusedDiskBytes\x126\n" +
	"\x17cpu_temperature_celsius\x18\x04 \x01(\x02R\x15cpuTemperatureCelsius\x12,\n" +
	"\x12running_task_count\x18\x05 \x01(\rR\x10runningTaskCount\"M\n" +
	"\x0fRegisterRequest\x12:\n" +
	"\vdevice_info\x18\x01 \x01(\v2\x19.localpilot.v1.DeviceInfoR\n" +
	"deviceInfo\"e\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x124\n" +
	"\x16heartbeat_interval_sec\x18\x02 \x01(\rR\x14heartbeatIntervalSec\"t\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12C\n" +
	"\x0eresource_usage\x18\x02 \x01(\v2\x1c.localpilot.v1.ResourceUsageR\rresourceUsage\"\x13\n" +
	"\x11HeartbeatResponse\"H\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"0\n" +
	"\x12DeregisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xb9\x02\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x128\n" +
	"\x03env\x18\x04 \x03(\v2&.localpilot.v1.ExecuteRequest.EnvEntryR\x03env\x12&\n" +
	"\x0finput_file_urls\x18\x05 \x03(\tR\rinputFileUrls\x12F\n" +
	"\x0fresource_limits\x18\x06 \x01(\v2\x1d.localpilot.v1.ResourceLimitsR\x0eresourceLimits\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\bLogChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12:\n" +
	"\vstream_type\x18\x02 \x01(\x0e2\x19.localpilot.v1.StreamTypeR\n" +
	"streamType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\x12\x17\n" +
	"\aseq_num\x18\x05 \x01(\x03R\x06seqNum\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"0\n" +
	"\x12CancelTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*Y\n" +
	"\n" +
	"StreamType\x12\x1b\n" +
	"\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STREAM_TYPE_STDOUT\x10\x01\x12\x16\n" +
	"\x12STREAM_TYPE_STDERR\x10\x022\xff\x01\n" +
	"\rDeviceService\x12K\n" +
	"\bRegister\x12\x1e.localpilot.v1.RegisterRequest\x1a\x1f.localpilot.v1.RegisterResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.localpilot.v1.HeartbeatRequest\x1a .localpilot.v1.HeartbeatResponse\x12Q\n" +
	"\n" +
	"Deregister\x12 .localpilot.v1.DeregisterRequest\x1a!.localpilot.v1.DeregisterResponse2\xae\x01\n" +
	"\x14TaskExecutionService\x12C\n" +
	"\aExecute\x12\x1d.localpilot.v1.ExecuteRequest\x1a\x17.localpilot.v1.LogChunk0\x01\x12Q\n" +
	"\n" +
	"CancelTask\x12 .localpilot.v1.CancelTaskRequest\x1a!.localpilot.v1.CancelTaskResponseB:Z8github.com/localpilot/controller/pkg/proto/localpilot/v1b\x06proto3"

var (
	file_localpilot_v1_agent_proto_rawDescOnce sync.Once
	file_localpilot_v1_agent_proto_rawDescData []byte
)

func file_localpilot_v1_agent_proto_rawDescGZIP() []byte {
	file_localpilot_v1_agent_proto_rawDescOnce.Do(func() {
		file_localpilot_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localpilot_v1_agent_proto_rawDesc), len(file_localpilot_v1_agent_proto_rawDesc)))
	})
	return file_localpilot_v1_agent_proto_rawDescData
}

var file_localpilot_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_localpilot_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_localpilot_v1_agent_proto_goTypes = []any{
	(StreamType)(0),            // 0: localpilot.v1.StreamType
	(*DeviceInfo)(nil),         // 1: localpilot.v1.DeviceInfo
	(*ResourceUsage)(nil),      // 2: localpilot.v1.ResourceUsage
	(*RegisterRequest)(nil),    // 3: localpilot.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 4: localpilot.v1.RegisterResponse
	(*HeartbeatRequest)(nil),   // 5: localpilot.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 6: localpilot.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),  // 7: localpilot.v1.DeregisterRequest
	(*DeregisterResponse)(nil), // 8: localpilot.v1.DeregisterResponse
	(*ExecuteRequest)(nil),     // 9: localpilot.v1.ExecuteRequest
	(*LogChunk)(nil),           // 10: localpilot.v1.LogChunk
	(*CancelTaskRequest)(nil),  // 11: localpilot.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil), // 12: localpilot.v1.CancelTaskResponse
	nil,                        // 13: localpilot.v1.ExecuteRequest.EnvEntry
	(*ResourceLimits)(nil),     // 14: localpilot.v1.ResourceLimits
}
var file_localpilot_v1_agent_proto_depIdxs = []int32{
	1,  // 0: localpilot.v1.RegisterRequest.device_info:type_name -> localpilot.v1.DeviceInfo
	2,  // 1: localpilot.v1.HeartbeatRequest.resource_usage:type_name -> localpilot.v1.ResourceUsage
	13, // 2: localpilot.v1.ExecuteRequest.env:type_name -> localpilot.v1.ExecuteRequest.EnvEntry
	14, // 3: localpilot.v1.ExecuteRequest.resource_limits:type_name -> localpilot.v1.ResourceLimits
	0,  // 4: localpilot.v1.LogChunk.stream_type:type_name -> localpilot.v1.StreamType
	3,  // 5: localpilot.v1.DeviceService.Register:input_type -> localpilot.v1.RegisterRequest
	5,  // 6: localpilot.v1.DeviceService.Heartbeat:input_type -> localpilot.v1.HeartbeatRequest
	7,  // 7: localpilot.v1.DeviceService.Deregister:input_type -> localpilot.v1.DeregisterRequest
	9,  // 8: localpilot.v1.TaskExecutionService.Execute:input_type -> localpilot.v1.ExecuteRequest
	11, // 9: localpilot.v1.TaskExecutionService.CancelTask:input_type -> localpilot.v1.CancelTaskRequest
	4,  // 10: localpilot.v1.DeviceService.Register:output_type -> localpilot.v1.RegisterResponse
	6,  // 11: localpilot.v1.DeviceService.Heartbeat:output_type -> localpilot.v1.HeartbeatResponse
	8,  // 12: localpilot.v1.DeviceService.Deregister:output_type -> localpilot.v1.DeregisterResponse
	10, // 13: localpilot.v1.TaskExecutionService.Execute:output_type -> localpilot.v1.LogChunk
	12, // 14: localpilot.v1.TaskExecutionService.CancelTask:output_type -> localpilot.v1.CancelTaskResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_localpilot_v1_agent_proto_init() }
func file_localpilot_v1_agent_proto_init() {
	if File_localpilot_v1_agent_proto != nil {
		return
	}
	file_localpilot_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localpilot_v1_agent_proto_rawDesc), len(file_localpilot_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_localpilot_v1_agent_proto_goTypes,
		DependencyIndexes: file_localpilot_v1_agent_proto_depIdxs,
		EnumInfos:         file_localpilot_v1_agent_proto_enumTypes,
		MessageInfos:      file_localpilot_v1_agent_proto_msgTypes,
	}.Build()
	File_localpilot_v1_agent_proto = out.File
	file_localpilot_v1_agent_proto_goTypes = nil
	file_localpilot_v1_agent_proto_depIdxs = nil
}
