// ============================================================
// discovery.proto — 服务发现相关定义
//
// 为什么这个文件几乎是空的？
//   服务发现走的是 mDNS，不需要 Protobuf 定义。
//   这个文件的存在是为了：
//   1. 记录 mDNS 服务名（_localpilot._tcp），防止拼写错误
//   2. 预留将来替换 mDNS 为其他发现机制时的扩展点
//   3. 让 proto/ 目录结构完整——discovery 是三个核心子系统之一
//
// ============================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: localpilot/v1/discovery.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_localpilot_v1_discovery_proto protoreflect.FileDescriptor

const file_localpilot_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1dlocalpilot/v1/discovery.proto\x12\rlocalpilot.v12\x12\n" +
	"\x10DiscoveryServiceB:Z8github.com/localpilot/controller/pkg/proto/localpilot/v1b\x06proto3"

var file_localpilot_v1_discovery_proto_goTypes = []any{}
var file_localpilot_v1_discovery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_localpilot_v1_discovery_proto_init() }
func file_localpilot_v1_discovery_proto_init() {
	if File_localpilot_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localpilot_v1_discovery_proto_rawDesc), len(file_localpilot_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_localpilot_v1_discovery_proto_goTypes,
		DependencyIndexes: file_localpilot_v1_discovery_proto_depIdxs,
	}.Build()
	File_localpilot_v1_discovery_proto = out.File
	file_localpilot_v1_discovery_proto_goTypes = nil
	file_localpilot_v1_discovery_proto_depIdxs = nil
}
