// ============================================================
// task.proto — 任务模型定义
//
// 为什么任务模型单独一个文件？
//   任务的状态机、分片策略、资源约束这些概念是独立的领域模型。
//   agent.proto 依赖这里定义的 Task，discovery.proto 不依赖任何东西。
//   分离后各 proto 文件职责单一，变更影响范围可控。
// ============================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: localpilot/v1/task.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 1 // 已入队，等待调度
	TaskStatus_TASK_STATUS_ASSIGNED    TaskStatus = 2 // 已分配给设备，等待执行
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3 // 正在执行
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 4 // 执行成功
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5 // 执行失败
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 6 // 已取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_QUEUED",
		2: "TASK_STATUS_ASSIGNED",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_QUEUED":      1,
		"TASK_STATUS_ASSIGNED":    2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_COMPLETED":   4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_CANCELLED":   6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_localpilot_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_localpilot_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{0}
}

type ShardingStrategy int32

const (
	ShardingStrategy_SHARDING_STRATEGY_UNSPECIFIED ShardingStrategy = 0
	ShardingStrategy_SHARDING_STRATEGY_NONE        ShardingStrategy = 1 // 不可分片，整个任务在一台设备上执行
	ShardingStrategy_SHARDING_STRATEGY_RANGE       ShardingStrategy = 2 // 按数字范围分片（ffmpeg 按帧范围）
	ShardingStrategy_SHARDING_STRATEGY_CHUNK       ShardingStrategy = 3 // 按文件分片（文件列表分成 N 份）
	ShardingStrategy_SHARDING_STRATEGY_PARAM       ShardingStrategy = 4 // 按参数组合分片（网格搜索超参调优）
)

// Enum value maps for ShardingStrategy.
var (
	ShardingStrategy_name = map[int32]string{
		0: "SHARDING_STRATEGY_UNSPECIFIED",
		1: "SHARDING_STRATEGY_NONE",
		2: "SHARDING_STRATEGY_RANGE",
		3: "SHARDING_STRATEGY_CHUNK",
		4: "SHARDING_STRATEGY_PARAM",
	}
	ShardingStrategy_value = map[string]int32{
		"SHARDING_STRATEGY_UNSPECIFIED": 0,
		"SHARDING_STRATEGY_NONE":        1,
		"SHARDING_STRATEGY_RANGE":       2,
		"SHARDING_STRATEGY_CHUNK":       3,
		"SHARDING_STRATEGY_PARAM":       4,
	}
)

func (x ShardingStrategy) Enum() *ShardingStrategy {
	p := new(ShardingStrategy)
	*p = x
	return p
}

func (x ShardingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_localpilot_v1_task_proto_enumTypes[1].Descriptor()
}

func (ShardingStrategy) Type() protoreflect.EnumType {
	return &file_localpilot_v1_task_proto_enumTypes[1]
}

func (x ShardingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardingStrategy.Descriptor instead.
func (ShardingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                             // 任务唯一 ID（UUID，Controller 分配）
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                         // 人类可读的任务名，如 "视频A转码"
	Command         string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                                                   // 要执行的命令
	Args            []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`                                                                         // 命令参数
	Env             map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 环境变量
	InputFileUrls   []string               `protobuf:"bytes,6,rep,name=input_file_urls,json=inputFileUrls,proto3" json:"input_file_urls,omitempty"`                                // 输入文件 URL
	ResourceLimits  *ResourceLimits        `protobuf:"bytes,7,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`                               // 资源限制
	Sharding        *TaskSharding          `protobuf:"bytes,8,opt,name=sharding,proto3" json:"sharding,omitempty"`                                                                 // 分片策略（如果可分片）
	CreatedAtUnixMs int64                  `protobuf:"varint,9,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`                       // 创建时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_localpilot_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Task) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Task) GetInputFileUrls() []string {
	if x != nil {
		return x.InputFileUrls
	}
	return nil
}

func (x *Task) GetResourceLimits() *ResourceLimits {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

func (x *Task) GetSharding() *TaskSharding {
	if x != nil {
		return x.Sharding
	}
	return nil
}

func (x *Task) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

// ResourceLimits: 任务的资源约束
type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuLimit      float32                `protobuf:"fixed32,1,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`                 // CPU 核心数上限，0 表示不限
	MemLimitBytes uint64                 `protobuf:"varint,2,opt,name=mem_limit_bytes,json=memLimitBytes,proto3" json:"mem_limit_bytes,omitempty"` // 内存上限（字节），0 表示不限
	TimeoutSec    uint32                 `protobuf:"varint,3,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`            // 超时（秒），0 表示不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_localpilot_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetCpuLimit() float32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *ResourceLimits) GetMemLimitBytes() uint64 {
	if x != nil {
		return x.MemLimitBytes
	}
	return 0
}

func (x *ResourceLimits) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type TaskSharding struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Strategy    ShardingStrategy       `protobuf:"varint,1,opt,name=strategy,proto3,enum=localpilot.v1.ShardingStrategy" json:"strategy,omitempty"` // 分片策略
	TotalShards uint32                 `protobuf:"varint,2,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`            // 总分片数
	ShardIndex  uint32                 `protobuf:"varint,3,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`               // 当前子任务的索引（0-based）
	ShardKey    string                 `protobuf:"bytes,4,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`                      // 分片键，含义取决于策略
	// 子任务引用，用于在 Dashboard 上展示分片进度
	ChildTaskIds  []string `protobuf:"bytes,5,rep,name=child_task_ids,json=childTaskIds,proto3" json:"child_task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSharding) Reset() {
	*x = TaskSharding{}
	mi := &file_localpilot_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSharding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSharding) ProtoMessage() {}

func (x *TaskSharding) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSharding.ProtoReflect.Descriptor instead.
func (*TaskSharding) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskSharding) GetStrategy() ShardingStrategy {
	if x != nil {
		return x.Strategy
	}
	return ShardingStrategy_SHARDING_STRATEGY_UNSPECIFIED
}

func (x *TaskSharding) GetTotalShards() uint32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *TaskSharding) GetShardIndex() uint32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *TaskSharding) GetShardKey() string {
	if x != nil {
		return x.ShardKey
	}
	return ""
}

func (x *TaskSharding) GetChildTaskIds() []string {
	if x != nil {
		return x.ChildTaskIds
	}
	return nil
}

type TaskResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                    // 任务 ID
	Status           TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=localpilot.v1.TaskStatus" json:"status,omitempty"`                   // 最终状态
	ExitCode         int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                             // 进程退出码（-1 表示被信号杀死）
	OutputFileUrls   []string               `protobuf:"bytes,4,rep,name=output_file_urls,json=outputFileUrls,proto3" json:"output_file_urls,omitempty"`          // 输出文件下载地址
	ErrorMessage     string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                  // 错误信息（失败时）
	StartedAtUnixMs  int64                  `protobuf:"varint,6,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`    // 开始执行时间
	FinishedAtUnixMs int64                  `protobuf:"varint,7,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"` // 完成时间
	AttemptNumber    uint32                 `protobuf:"varint,8,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`              // 第几次尝试（用于追踪重试）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_localpilot_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetOutputFileUrls() []string {
	if x != nil {
		return x.OutputFileUrls
	}
	return nil
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *TaskResult) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

func (x *TaskResult) GetAttemptNumber() uint32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

type Checkpoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                 // 任务 ID
	SeqNum          int64                  `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`                                // checkpoint 序号
	AttemptNumber   uint32                 `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`           // 尝试次数
	StateData       []byte                 `protobuf:"bytes,4,opt,name=state_data,json=stateData,proto3" json:"state_data,omitempty"`                        // 任务自定义的状态数据
	OutputFileUrls  []string               `protobuf:"bytes,5,rep,name=output_file_urls,json=outputFileUrls,proto3" json:"output_file_urls,omitempty"`       // 已产生的中间文件
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"` // checkpoint 创建时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_localpilot_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_localpilot_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_localpilot_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *Checkpoint) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Checkpoint) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Checkpoint) GetAttemptNumber() uint32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *Checkpoint) GetStateData() []byte {
	if x != nil {
		return x.StateData
	}
	return nil
}

func (x *Checkpoint) GetOutputFileUrls() []string {
	if x != nil {
		return x.OutputFileUrls
	}
	return nil
}

func (x *Checkpoint) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

var File_localpilot_v1_task_proto protoreflect.FileDescriptor

const file_localpilot_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x18localpilot/v1/task.proto\x12\rlocalpilot.v1\"\x96\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12.\n" +
	"\x03env\x18\x05 \x03(\v2\x1c.localpilot.v1.Task.EnvEntryR\x03env\x12&\n" +
	"\x0finput_file_urls\x18\x06 \x03(\tR\rinputFileUrls\x12F\n" +
	"\x0fresource_limits\x18\a \x01(\v2\x1d.localpilot.v1.ResourceLimitsR\x0eresourceLimits\x127\n" +
	"\bsharding\x18\b \x01(\v2\x1b.localpilot.v1.TaskShardingR\bsharding\x12+\n" +
	"\x12created_at_unix_ms\x18\t \x01(\x03R\x0fcreatedAtUnixMs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tcpu_limit\x18\x01 \x01(\x02R\bcpuLimit\x12&\n" +
	"\x0fmem_limit_bytes\x18\x02 \x01(\x04R\rmemLimitBytes\x12\x1f\n" +
	"\vtimeout_sec\x18\x03 \x01(\rR\n" +
	"timeoutSec\"\xd2\x01\n" +
	"\fTaskSharding\x12;\n" +
	"\bstrategy\x18\x01 \x01(\x0e2\x1f.localpilot.v1.ShardingStrategyR\bstrategy\x12!\n" +
	"\ftotal_shards\x18\x02 \x01(\rR\vtotalShards\x12\x1f\n" +
	"\vshard_index\x18\x03 \x01(\rR\n" +
	"shardIndex\x12\x1b\n" +
	"\tshard_key\x18\x04 \x01(\tR\bshardKey\x12$\n" +
	"\x0echild_task_ids\x18\x05 \x03(\tR\fchildTaskIds\"\xc7\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.localpilot.v1.TaskStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12(\n" +
	"\x10output_file_urls\x18\x04 \x03(\tR\x0eoutputFileUrls\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12+\n" +
	"\x12started_at_unix_ms\x18\x06 \x01(\x03R\x0fstartedAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\a \x01(\x03R\x10finishedAtUnixMs\x12%\n" +
	"\x0eattempt_number\x18\b \x01(\rR\rattemptNumber\"\xdb\x01\n" +
	"\n" +
	"Checkpoint\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x03R\x06seqNum\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\rR\rattemptNumber\x12\x1d\n" +
	"\n" +
	"state_data\x18\x04 \x01(\fR\tstateData\x12(\n" +
	"\x10output_file_urls\x18\x05 \x03(\tR\x0eoutputFileUrls\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMs*\xc2\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_ASSIGNED\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x06*\xa8\x01\n" +
	"\x10ShardingStrategy\x12!\n" +
	"\x1dSHARDING_STRATEGY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SHARDING_STRATEGY_NONE\x10\x01\x12\x1b\n" +
	"\x17SHARDING_STRATEGY_RANGE\x10\x02\x12\x1b\n" +
	"\x17SHARDING_STRATEGY_CHUNK\x10\x03\x12\x1b\n" +
	"\x17SHARDING_STRATEGY_PARAM\x10\x04B:Z8github.com/localpilot/controller/pkg/proto/localpilot/v1b\x06proto3"

var (
	file_localpilot_v1_task_proto_rawDescOnce sync.Once
	file_localpilot_v1_task_proto_rawDescData []byte
)

func file_localpilot_v1_task_proto_rawDescGZIP() []byte {
	file_localpilot_v1_task_proto_rawDescOnce.Do(func() {
		file_localpilot_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localpilot_v1_task_proto_rawDesc), len(file_localpilot_v1_task_proto_rawDesc)))
	})
	return file_localpilot_v1_task_proto_rawDescData
}

var file_localpilot_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_localpilot_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_localpilot_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),        // 0: localpilot.v1.TaskStatus
	(ShardingStrategy)(0),  // 1: localpilot.v1.ShardingStrategy
	(*Task)(nil),           // 2: localpilot.v1.Task
	(*ResourceLimits)(nil), // 3: localpilot.v1.ResourceLimits
	(*TaskSharding)(nil),   // 4: localpilot.v1.TaskSharding
	(*TaskResult)(nil),     // 5: localpilot.v1.TaskResult
	(*Checkpoint)(nil),     // 6: localpilot.v1.Checkpoint
	nil,                    // 7: localpilot.v1.Task.EnvEntry
}
var file_localpilot_v1_task_proto_depIdxs = []int32{
	7, // 0: localpilot.v1.Task.env:type_name -> localpilot.v1.Task.EnvEntry
	3, // 1: localpilot.v1.Task.resource_limits:type_name -> localpilot.v1.ResourceLimits
	4, // 2: localpilot.v1.Task.sharding:type_name -> localpilot.v1.TaskSharding
	1, // 3: localpilot.v1.TaskSharding.strategy:type_name -> localpilot.v1.ShardingStrategy
	0, // 4: localpilot.v1.TaskResult.status:type_name -> localpilot.v1.TaskStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_localpilot_v1_task_proto_init() }
func file_localpilot_v1_task_proto_init() {
	if File_localpilot_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localpilot_v1_task_proto_rawDesc), len(file_localpilot_v1_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_localpilot_v1_task_proto_goTypes,
		DependencyIndexes: file_localpilot_v1_task_proto_depIdxs,
		EnumInfos:         file_localpilot_v1_task_proto_enumTypes,
		MessageInfos:      file_localpilot_v1_task_proto_msgTypes,
	}.Build()
	File_localpilot_v1_task_proto = out.File
	file_localpilot_v1_task_proto_goTypes = nil
	file_localpilot_v1_task_proto_depIdxs = nil
}
